const Core = (() => {
  const DB_NAME='official-remove-bg-history', DB_VERSION=1, STORE='history', MAX_HISTORY=30, MAX_UPLOAD_BYTES=22*1024*1024;
  let dbPromise=null, toastTimer=null;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
  function settings(){const q=localStorage.getItem('rbg-quality')==='preview'?'preview':'auto';const valid=['auto','graphic','person','product','animal','car','transportation'];const s=valid.includes(localStorage.getItem('rbg-subject'))?localStorage.getItem('rbg-subject'):'auto';return{quality:q,subject:s}}
  function syncControls(){const s=settings();$$('[data-quality]').forEach(b=>b.classList.toggle('active',b.dataset.quality===s.quality));$$('[data-subject]').forEach(b=>b.classList.toggle('active',b.dataset.subject===s.subject))}
  function bindSettings(){ $$('[data-quality]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('rbg-quality',b.dataset.quality);syncControls()})); $$('[data-subject]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('rbg-subject',b.dataset.subject);syncControls()})); syncControls() }
  function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const st=db.createObjectStore(STORE,{keyPath:'id'});st.createIndex('createdAt','createdAt')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
  async function put(record){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
  async function get(id){if(!id)return null;const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
  async function getAll(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>resolve(req.result.sort((a,b)=>b.createdAt-a.createdAt));req.onerror=()=>reject(req.error)})}
  async function del(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
  async function clear(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
  async function saveHistory(record){const saved={...record,id:record.id||`${Date.now()}-${crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}`,createdAt:record.createdAt||Date.now()};await put(saved);const all=await getAll();for(const old of all.slice(MAX_HISTORY))await del(old.id);localStorage.setItem('rbg-current-record',saved.id);return saved}
  const currentRecordId=()=>localStorage.getItem('rbg-current-record'); const setCurrentRecord=id=>id&&localStorage.setItem('rbg-current-record',id);
  async function responseError(response){try{const d=await response.json();return d.error||`Request failed (${response.status})`}catch{return`Request failed (${response.status})`}}
  function validateFile(file){if(!file||!file.type?.startsWith('image/'))throw new Error('Please choose an image file.');if(file.size>MAX_UPLOAD_BYTES)throw new Error('Image is larger than the remove.bg 22 MB API limit.')}
  async function createJobFromFile(file){validateFile(file);const s=settings();const form=new FormData();form.append('image',file,file.name||'pasted-image.png');form.append('size',s.quality);form.append('type',s.subject);const res=await fetch('/api/jobs',{method:'POST',body:form});if(!res.ok)throw new Error(await responseError(res));return res.json()}
  async function createJobFromUrl(url){const s=settings();const res=await fetch('/api/jobs-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,size:s.quality,type:s.subject})});if(!res.ok)throw new Error(await responseError(res));return res.json()}
  function goProcessing(job){const q=new URLSearchParams({id:job.id,name:job.name||'image.png',size:job.size||'auto',subject:job.subjectType||'auto'});location.assign(`/processing?${q}`)}
  async function submitFile(file){const job=await createJobFromFile(file);goProcessing(job)} async function submitUrl(url){const job=await createJobFromUrl(url);goProcessing(job)}
  function fileFromClipboardData(data){if(!data)return null;for(const item of [...(data.items||[])]){if(item.kind==='file'&&item.type?.startsWith('image/')){const blob=item.getAsFile();if(blob){const ext=(blob.type.split('/')[1]||'png').replace('jpeg','jpg');return new File([blob],`pasted-${Date.now()}.${ext}`,{type:blob.type||'image/png'})}}}return[...(data.files||[])].find(f=>f.type?.startsWith('image/'))||null}
  function isHttpUrl(v){try{const u=new URL((v||'').trim());return u.protocol==='http:'||u.protocol==='https:'}catch{return false}}
  function urlFromClipboard(data){if(!data)return null;const html=data.getData?.('text/html')||'';if(html){try{const doc=new DOMParser().parseFromString(html,'text/html');const src=doc.querySelector('img')?.getAttribute('src')||'';if(isHttpUrl(src))return src}catch{}}const uri=(data.getData?.('text/uri-list')||'').split(/\r?\n/).find(v=>v&&!v.startsWith('#'))||'';if(isHttpUrl(uri))return uri.trim();const text=(data.getData?.('text/plain')||'').trim();return isHttpUrl(text)?text:null}
  async function readClipboard(){if(!navigator.clipboard?.read)throw new Error('Press Ctrl+V to paste the copied image.');const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(t=>t.startsWith('image/'));if(type){const blob=await item.getType(type);const ext=(blob.type.split('/')[1]||'png').replace('jpeg','jpg');return{file:new File([blob],`pasted-${Date.now()}.${ext}`,{type:blob.type||'image/png'})}}}for(const item of items){if(item.types.includes('text/plain')){const text=(await(await item.getType('text/plain')).text()).trim();if(isHttpUrl(text))return{url:text}}}throw new Error('No image found in clipboard.')}
  function bindPaste(){document.addEventListener('paste',async e=>{const target=e.target;if(target&&(target.matches?.('input,textarea')||target.isContentEditable))return;const file=fileFromClipboardData(e.clipboardData);const url=file?null:urlFromClipboard(e.clipboardData);if(!file&&!url)return;e.preventDefault();try{if(file)await submitFile(file);else await submitUrl(url)}catch(err){toast(err.message)}})}
  async function copyPng(blob){if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw new Error('Image copy is not supported in this browser.');await navigator.clipboard.write([new ClipboardItem({'image/png':blob})])}
  function downloadPng(blob,filename='removed-background.png'){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename.replace(/\.[^.]+$/,'')+'-no-bg.png';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
  async function loadAccountBadge(){const badge=$('#creditBadge');if(!badge)return;try{const res=await fetch('/api/account',{cache:'no-store'});if(!res.ok){badge.textContent=res.status===503?'Add API Key':'API';return}const d=await res.json();const total=d.credits?.total,free=d.freeCalls;if(typeof total==='number'&&total>0)badge.textContent=`${total} credits`;else if(typeof free==='number')badge.textContent=`${free} free calls`;else badge.textContent='API Ready'}catch{badge.textContent='API'}}
  function setup(){bindSettings();bindPaste();loadAccountBadge()}
  return{$,$$,toast,settings,syncControls,setup,readClipboard,createJobFromFile,createJobFromUrl,submitFile,submitUrl,goProcessing,saveHistory,get,getAll,del,clear,currentRecordId,setCurrentRecord,copyPng,downloadPng,responseError}
})();
window.addEventListener('DOMContentLoaded',()=>Core.setup());
